config/routes.rb
Rails.application.routes.draw do
 

   root 'welcome#index'
   resources :albums do
   	resources :photos do 
   		collection do
   			get :search

   		end
   	end
   end
  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	validates :title, presence: true,
                   length: { minimum: 3 }
    validates :description, presence: true,
                   length: { minimum: 5 }
   	
	belongs_to :user
	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_attached_file :image
    validates_attachment :image,content_type:{content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}
	belongs_to :album
	has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :photos
	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController 
  skip_before_filter :verify_authenticity_token, :only => :create
  def index
    @albums = current_user.albums
  end

  def new
    @album = Album.new
  end

  def create
     @album = current_user.albums.new(album_params)
     if @album.save
         #flash[:notice] = "Successfully created album!"
         redirect_to [:albums]
     else
         render "new"
     end
  end

  def show
    @album = Album.find(params[:id])
    @photo = @album.photos.new
  end

  def edit
  end

  def update
  end

  def destroy
    @album = Album.find(params[:id]).destroy
    redirect_to albums_path(@albums)
    
  end
  private
  def album_params
    params.require(:album).permit(:title, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend:true, with: :exception
  before_action :authenticate_user!
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :check_album
  def index
  end

  def new
  	@photo = Photo.new
  end

  def create
  	@photo = @album.photos.new(photos_params)
    if @photo.save
      if params[:tags]
        (params[:tags].split(',')).each do |tag|
        @photo.tags.create(title: tag)
        end
      end
      flash[:success] = "The photo was added!"
      redirect_to album_path(@album)
    else
      render 'new'
    end
  end

  def show
  	@photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
   # debugger
   @photo = @album.photos.find(params[:id])
    if @photo.update_attributes(photos_params)
      redirect_to @album
    else
      render :edit
    end
  end

  
  def destroy
  	#album=Album.find(params[:album_id])
    @photo = Photo.find(params[:id]).destroy
    redirect_to album_path(@album.id)
  end

  def search
    @photo = @album.photos.joins(:tags).where("tags.title like?","%#{params[:tag]}%")
    #@photos = Photo.joins(:tags).where(tags:{title: params[:tag]})
  end


 private

 def photos_params
	params.require(:photo).permit(:image)
 end

 def check_album
  @album=Album.find(params[:album_id])
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/index.html.erb
<h1>Album List</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    
  </tr>

  <% @albums.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.description %></td>
      
      <td><%= link_to 'Show', album_path(album) %></td>
      <td><%= link_to 'Delete', album_path(album), :method => :delete %></td>
     
    </tr>
  <% end %>
</table>


<%= link_to 'New album', new_album_path %>

app/views/albums/new.html.erb
<h1>Album</h1>

<%= form_for @album, url: albums_path, method:"photo" do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/albums/show.html.erb
<h1>Show album details</h1>
<table>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
	<tr>
      <td><%= @album.title %></td>
      <td><%= @album.description %></td>
      <% @album.photos.each do |photo|%>
        <% if photo.id.present? %>
          <td><%= photo.image_file_name %>
            <%=link_to 'Show',album_photo_path(album_id: @album.id, id: photo.id)%>
            <%#= link_to 'Delete', album_photo_path(album_id: @album.id, id: photo.id), method: :delete%>
          </td>
        <%end%>
      <%end%>
    </tr>
  </table>
      <%= form_tag search_album_photos_path(album_id: @album), :method => :get do %>
       <%= text_field_tag :tag,"",placeholder: "Search Tags"%>
       <%= submit_tag "Search"%>
       <%end%>
<%= form_for @photo, url: album_photos_path(@album), :method => :post do|f| %>

<p> 

    <%= f.label :image %><br>
    <%= f.file_field :image %><br>
    <%= f.label :tag %><br>
    <%= text_field_tag :tags %><br>
    <%= f.hidden_field :album_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

    <%= yield %>
  </body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/edit.html.erb
<h1>UploadPhoto</h1>
<%= form_for @photo, url: album_photo_path(@album, @photo), :method => :put do|f| %>
<p>
	<%= f.label :image %><br>
	<%= f.file_field :image %><br>
	<%= f.submit 'Upload Photo' %>
   		or
   	<%= link_to 'Cancel', [@album, @photo] %>
 </p>

<% end %>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<h1>Photos#new</h1>
<p>Find me in app/views/photos/new.html.erb</p>

app/views/photos/search.html.erb
<% @photo.each do |photo|%>
        <% if photo.id.present? %>
          <td><%= photo.image_file_name %>
            <%=link_to 'Show',album_photo_path(album_id: @album.id, id: photo.id)%>
          </td>
        <%end%>
      <%end%>

app/views/photos/show.html.erb
<h1>MyPhotos</h1>
	
     <td><%= image_tag(@photo.image.url, width: 100, height: 100)%><br>
     </td>
     <%= link_to 'Tags#', album_photo_path(@album, @photo)%>
     <%#aaj29%>
     <%= @photo.tags.map(&:title).join(",")%><br>

     <%= link_to 'Edit', edit_album_photo_path(@album, @photo)%><br>

    <%= link_to 'Delete', album_photo_path(@album, @photo), method: :delete%><br>
	

app/views/welcome/index.html.erb
<h1>Create album</h1>
<%= link_to 'Click', albums_path %>